@startuml
digraph G {
  1 [ label="kh" ];
  2 [ label="tc" ];
  3 [ label="qp" ];
  4 [ label="de" ];
  5 [ label="cg" ];
  6 [ label="ka" ];
  7 [ label="co" ];
  8 [ label="yn" ];
  9 [ label="aq" ];
  10 [ label="ub" ];
  11 [ label="tb" ];
  12 [ label="vc" ];
  13 [ label="wh" ];
  14 [ label="ta" ];
  15 [ label="td" ];
  16 [ label="wq" ];
  1 -> 2;
  1 -> 3;
  1 -> 10;
  1 -> 14;
  2 -> 1;
  2 -> 13;
  2 -> 15;
  2 -> 7;
  3 -> 1;
  3 -> 10;
  3 -> 15;
  3 -> 13;
  4 -> 5;
  4 -> 7;
  4 -> 14;
  4 -> 6;
  5 -> 4;
  5 -> 11;
  5 -> 8;
  5 -> 9;
  6 -> 7;
  6 -> 11;
  6 -> 14;
  6 -> 4;
  7 -> 6;
  7 -> 14;
  7 -> 4;
  7 -> 2;
  8 -> 9;
  8 -> 5;
  8 -> 13;
  8 -> 15;
  9 -> 8;
  9 -> 12;
  9 -> 5;
  9 -> 16;
  10 -> 3;
  10 -> 1;
  10 -> 16;
  10 -> 12;
  11 -> 5;
  11 -> 6;
  11 -> 16;
  11 -> 12;
  12 -> 9;
  12 -> 10;
  12 -> 16;
  12 -> 11;
  13 -> 2;
  13 -> 15;
  13 -> 8;
  13 -> 3;
  14 -> 7;
  14 -> 6;
  14 -> 4;
  14 -> 1;
  15 -> 2;
  15 -> 13;
  15 -> 3;
  15 -> 8;
  16 -> 11;
  16 -> 10;
  16 -> 9;
  16 -> 12;
}
@enduml